version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  app:
    build: ./
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_PORT=5432
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=db
      - POSTGRES_DB=fastapi
      - POSTGRES_HOST=postgres
      - POSTGRES_HOSTNAME=postgres
    volumes:
      - .:/app
    restart: always

volumes:
  postgres-db: